# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Create Syntax Hightlight

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set VIM environment
      run: |
        export GIT_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        apt install -y vim
        cd build/output/
        vim -c "put =expand('\$VIMRUNTIME')" -c "wq! .vimruntime"
        export VIMRUNTIME=$(cat .vimruntime)
        cp -r ../prizmbasic.vim $VIMRUNTIME/syntax/
    - name: Apply syntax highlight
      run: |
        for filename in $(ls ../../src/prizmbasic/); do source ../2html.sh ../../src/prizmbasic/$filename > ./$filename.html; done
        cd ..
    - name: Run node script
      run: |
        npm install
        npm build && npm start
    - name: Push to main
      run: |
        cd ..
        git fetch origin main
        git checkout main
        git add -f ./src/markdown/*.md
    - name: Merge deploy branch into main
      run: |
      git merge --no-ff deploy -m "$GIT_COMMIT_MESSAGE"
    - name: Push changes to main branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main