# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Create Syntax Hightlight

on:
  push:
    branches: [ "deploy" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    concurrency:
      group: my-global-job
      cancel-in-progress: true

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Set VIM environment
      run: |
        git log -1 --pretty=%B > ~/GIT_COMMIT_MESSAGE
        sudo apt install -y vim
        cd build/output/
        vim -c "put =expand('\$VIMRUNTIME')" -c "wq! .vimruntime"
        export VIMRUNTIME=$(cat .vimruntime)
        sudo cp -r ../prizmbasic.vim $VIMRUNTIME/syntax/
    - name: Apply syntax highlight
      run: |
        cd build/output/
        for filename in $(ls ../../src/prizmbasic/); do source ../2html.sh ../../src/prizmbasic/$filename > ./$filename.html; done
    - name: Run node script
      run: |
        cd build/
        npm install
        npm run build && npm run start
    - name: Push to main
      run: |
        export GIT_COMMIT_MESSAGE=$(cat ~/GIT_COMMIT_MESSAGE)
        git config --global user.email "GitHub Actions"
        git config --global user.name "actions@github.com"
        git fetch origin main
        git checkout main
        git rm -r --cached .
        git add .
        git add -f ./src/markdown/*.md
        git commit -m "$GIT_COMMIT_MESSAGE"
    - name: Merge deploy branch into main
      run: |
        export GIT_COMMIT_MESSAGE=$(cat ~/GIT_COMMIT_MESSAGE)
        git merge --no-ff deploy -m "$GIT_COMMIT_MESSAGE" --allow-unrelated-histories
    - name: Push changes to main branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main